Added missing imports and increased the minimum cmake version.
I've spent hours trying to compile the `master` branch (AKA version 2.0)
on my Linux machine. This code is over a decade old, and compiling it on
a modern system with newer compiler and library versions is proving
challenging.

First, CMake dropped support for anything older than 3.5:
<https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features>

Then, a bunch of C++ and Boost symbols now require explicit include,
while in the past the toolchain was more lenient.

I also had to add the `::` prefix to `HR_UNUSED` due to the C++
namespaces.

Still, after all of these changes, the code still doesn't compile, and I
don't know how to solve the remaining issues:

`engine/Display/PickList.h`:

> error: could not convert […] from ‘optional<int>’ to ‘optional<const int&>’

`client/Game2/HoverScript/ElemBinding.cpp` and
`client/Game2/HoverScript/TrackPeer.cpp`:

> error: ‘module’ was not declared in this scope
>
> error: ‘class_’ was not declared in this scope